// Лабораторна №6 ВПР/App.vue
<template>
  <div id="app">
    <nav class="header">
      <div class="logo"> ElectroShop</div>
      <div class="nav-links">
        <router-link to="/" class="link">Каталог</router-link>
        <router-link to="/cart" class="link">
          Кошик <span class="badge">{{ cart.items.length }}</span>
        </router-link>
      </div>
    </nav>
    <div class="container">
      <router-view />
    </div>
  </div>
</template>

<script setup>
import { useCartStore } from './stores/useCartStore'
const cart = useCartStore()
</script>

<style>
body { margin: 0; font-family: sans-serif; background: #f8f9fa; }
.header { background: #2c3e50; color: white; padding: 15px 50px; display: flex; justify-content: space-between; align-items: center; }
.link { color: white; text-decoration: none; margin-left: 20px; }
.badge { background: #42b983; padding: 2px 8px; border-radius: 10px; font-size: 0.8rem; }
.container { max-width: 1100px; margin: 30px auto; padding: 0 20px; }
</style>

// Лабораторна №7 ВПР/App.tsx
import React, { useState } from 'react';
import { Routes, Route, Link } from 'react-router-dom';
import CatalogPage from './pages/CatalogPage';

function App() {
  const [cart, setCart] = useState<any[]>([]);

  const addToCart = (product: any) => {
    setCart(prev => [...prev, product]);
  };

  return (
    <div style={{ fontFamily: 'Arial, sans-serif' }}>
      <header style={{ 
        background: '#2c3e50', 
        color: 'white', 
        padding: '15px 5%', 
        display: 'flex', 
        justifyContent: 'space-between', 
        alignItems: 'center' 
      }}>
        <Link to="/" style={{ color: 'white', textDecoration: 'none', fontSize: '22px', fontWeight: 'bold' }}>
          ⚡ ElectroShop
        </Link>
        <div style={{ fontSize: '16px' }}>
          🛒 Кошик: <strong>{cart.length}</strong> | Сума: {cart.reduce((sum, item) => sum + item.price, 0)} грн
        </div>
      </header>

      <main style={{ padding: '20px 5%' }}>
        <Routes>
          <Route path="/" element={<CatalogPage onAddToCart={addToCart} />} />
        </Routes>
      </main>
    </div>
  );
}

export default App;
